name: SonarQube Scan

on:
  push:
    branches:
      - main

jobs:
  sonar:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Cache SonarQube scanner
        uses: actions/cache@v4
        with:
          path: ~/.sonar/cache
          key: sonar-scanner-cli-7.1.0.4889-Linux-X64

      - name: Install Sonar Scanner
        run: |
          mkdir -p ${{ runner.temp }}/sonarscanner
          cd ${{ runner.temp }}/sonarscanner
          wget https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-7.1.0.4889-linux-x64.zip
          unzip -q sonar-scanner-cli-7.1.0.4889-linux-x64.zip
          echo "${{ runner.temp }}/sonarscanner/sonar-scanner-7.1.0.4889-linux-x64/bin" >> $GITHUB_PATH

      - name: Run Sonar Scanner
        run: |
          sonar-scanner \
          -Dsonar.projectKey=sample-sonar \
          -Dsonar.sources=. \
          -Dsonar.host.url=${{ secrets.SONAR_HOST_URL }} \
          -Dsonar.login=${{ secrets.SONAR_TOKEN }}
